// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.943
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"strconv"

	"scavenger/internal/models"
)

func StudentRegistrationPage(groups []models.Group) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"ru\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>Регистрация</title><link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\"></head><body class=\"bg-light\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Alerts().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<div class=\"container mt-4 vh-100 d-flex justify-content-center\"><div class=\"card shadow-sm\"><div class=\"card-header bg-primary text-white text-center\"><h4 class=\"card-title mb-0\"><i class=\"fas fa-user-graduate me-2\"></i> Регистрация</h4></div><div class=\"card-body p-4\"><div class=\"alert alert-info mb-4\"><h6 class=\"alert-heading\"><i class=\"fas fa-info-circle me-2\"></i> Информация о регистрации</h6><p class=\"mb-0\">Заполните форму ниже для создания учетной записи студента.  После регистрации вы сможете загружать лабораторные работы.</p></div><form method=\"POST\" action=\"/register\"><div class=\"row\"><div class=\"col-md-6\"><div class=\"mb-3\"><label class=\"form-label\">Логин *</label> <input type=\"text\" class=\"form-control\" name=\"username\" required placeholder=\"Придумайте логин\"><div class=\"form-text\">Логин должен быть уникальным</div></div></div><div class=\"col-md-6\"><div class=\"mb-3\"><label class=\"form-label\">Пароль *</label> <input type=\"password\" class=\"form-control\" name=\"password\" required placeholder=\"Придумайте пароль\"><div class=\"form-text\">Минимум 6 символов</div></div></div></div><div class=\"mb-3\"><label class=\"form-label\">ФИО *</label> <input type=\"text\" class=\"form-control\" name=\"name\" required placeholder=\"Фамилия Имя Отчество\"></div><div class=\"mb-4\"><label class=\"form-label\">Группа *</label> <select class=\"form-select\" name=\"group_id\" required><option value=\"\">Выберите группу</option> ")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		for _, group := range groups {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<option value=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var2 string
			templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(strconv.Itoa(group.ID))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/student_register.templ`, Line: 85, Col: 46}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 string
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(group.Name)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/student_register.templ`, Line: 86, Col: 21}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</option>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "</select><div class=\"form-text\">Выберите свою учебную группу</div></div><div class=\"d-grid gap-2\"><button type=\"submit\" class=\"btn btn-primary btn-lg\"><i class=\"fas fa-user-plus me-2\"></i> Зарегистрироваться</button> <a href=\"/login\" class=\"btn btn-outline-secondary\"><i class=\"fas fa-arrow-left me-2\"></i> Вернуться к входу</a></div></form><!-- Дополнительная информация --><div class=\"mt-4 pt-4 border-top\"><h6 class=\"text-muted\">Что после регистрации?</h6><ul class=\"small text-muted\"><li>Вы сможете загружать лабораторные работы</li><li>Просматривать статус проверки работ</li><li>Получать комментарии преподавателя</li></ul></div></div></div></div><script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js\"></script><script>\n\t\tvar toastElList = [].slice.call(document.querySelectorAll('.toast[autoshow]'))\n\n\t\tvar toastList = toastElList.map(function (toastEl) {\n\t\t\ttoastEl.removeAttribute('autoshow');\n\t\t\tvar toast = new bootstrap.Toast(toastEl)\n\t\t\ttoast.show()\n\t\t\treturn toast\n\t\t})\n\n\t\ttoastElList.forEach(function(toastEl) {\n\t\t\ttoastEl.addEventListener('hidden.bs.toast', function() {\n\t\t\t\tthis.remove()\n\t\t\t})\n\t\t})\n\t</script></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
