server:
  port: "8080"
  upload_path: "./uploads"
  download_path: "./download"

auth:
  session_secret: "123"

users:
  - username: "admin"
    password: "ghjgecr123"
    role: "admin"

  - username: "sa502-ivanov"
    password: "123"
    role: "student"
    group: "СА-502"

groups:
  - name: "СА-502"
    disciplines:
      - "Основы алгоритмизации и программирования"
      - "Основы проектирования баз данных"

disciplines:
  - name: "Основы алгоритмизации и программирования"
    id: "1"
    labs:
      - name: "ЛР 1. Построение алгоритмов и блок-схем"
        id: "1"
        path: "labs/prog/lab1.pdf"

  - name: "Основы проектирования баз данных"
    id: "2"
    labs:
      - name: "ЛР 1. Построение ER-диаграмм"
        id: "2"
        path: "labs/db/lab1.pdf"
