server:
    port: "1234"
    upload_path: ./uploads
auth:
    session_secret: "123"
database:
    data_source: "scavanger.db"
    migrations_path: "./migrations"
filestorage:
    base_path: "storage"
    base_url: "files"

test_data:
  roles:
    admin:
      - username: admin
        name: Admin
        password: ghjgecr123
    student:
      СА-502:
        - username: "sa502-ivanov"
          name: Ivanov I.I.
          password: 123
      Ш-208:
        - username: "sh208-petrov"
          name: Petrov P.P.
          password: 321

        - username: "sh280-sidorova"
          name: Sidorova S.S.
          password: 123321
