server:
    port: "8080"
auth:
    session_secret: "123"
database:
    data_source: "scavanger.db"
    migrations_path: "./migrations"
filestorage:
    base_path: "storage"
    base_url: "files"

test_data:
  roles:
    admin:
      - username: admin
        name: Admin
        password: ghjgecr123
