server:
    port: "8080"
auth:
    session_secret: "your-secret-key"
database:
    data_source: "scavanger.db"
    migrations_path: "./migrations"
filestorage:
    base_path: "storage"
    base_url: "files"

test_data:
  roles:
    admin:
      - username: teacher
        name: Teacher
        password: teacher123
