// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func EnterCode() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"container vh-100 d-flex align-items-center justify-content-center\"><div class=\"card shadow\" style=\"width: 400px;\"><div class=\"card-body p-4\"><h3 class=\"card-title text-center mb-4\"><i class=\"fas fa-graduation-cap text-primary\"></i><br>Регистрация по приглашению</h3><p class=\"text-muted text-center small mb-4\">Введите код приглашения и email, указанный при получении кода</p><form action=\"/register\" method=\"post\"><div class=\"mb-3\"><label class=\"form-label\">Код приглашения</label> <input type=\"text\" class=\"form-control\" name=\"code\" required placeholder=\"XXXXXX\"></div><div class=\"mb-3\"><label class=\"form-label\">Email</label> <input type=\"email\" class=\"form-control\" name=\"email\" required placeholder=\"user@example.com\"></div><button type=\"submit\" class=\"btn btn-primary w-100\">Продолжить</button></form><div class=\"text-center mt-3\"><a href=\"/login\" class=\"text-decoration-none small\">Вернуться ко входу</a></div></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
