// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package admin

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"fmt"

	"web-service/internal/models"
)

func Dashboard(user models.User, stats models.AdminDashboardStats) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"container-fluid mt-4\"><div class=\"row mb-4\"><div class=\"col\"><h1 class=\"h2\"><i class=\"fas fa-tachometer-alt me-2\"></i>Панель управления</h1><p class=\"text-muted\">Обзор системы управления учебным процессом</p></div></div><!-- Статистика --><div class=\"row mb-4\"><div class=\"col-md-3\"><div class=\"card border-primary\"><div class=\"card-body\"><div class=\"d-flex justify-content-between align-items-center\"><div><h6 class=\"card-title text-muted\">Студенты</h6><h3 class=\"mb-0\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("%d", stats.TotalStudents))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/views/pages/admin/dashboard.templ`, Line: 28, Col: 64}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</h3></div><div class=\"bg-primary text-white rounded-circle p-3\"><i class=\"fas fa-users fa-2x\"></i></div></div><small class=\"text-muted\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("%d ожидают подтверждения", stats.PendingStudents))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/views/pages/admin/dashboard.templ`, Line: 35, Col: 90}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</small></div></div></div><div class=\"col-md-3\"><div class=\"card border-success\"><div class=\"card-body\"><div class=\"d-flex justify-content-between align-items-center\"><div><h6 class=\"card-title text-muted\">Преподаватели</h6><h3 class=\"mb-0\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var4 string
		templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("%d", stats.TotalTeachers))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/views/pages/admin/dashboard.templ`, Line: 47, Col: 64}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</h3></div><div class=\"bg-success text-white rounded-circle p-3\"><i class=\"fas fa-chalkboard-teacher fa-2x\"></i></div></div><small class=\"text-muted\">Активные преподаватели</small></div></div></div><div class=\"col-md-3\"><div class=\"card border-warning\"><div class=\"card-body\"><div class=\"d-flex justify-content-between align-items-center\"><div><h6 class=\"card-title text-muted\">Группы</h6><h3 class=\"mb-0\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var5 string
		templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("%d", stats.TotalGroups))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/views/pages/admin/dashboard.templ`, Line: 64, Col: 62}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</h3></div><div class=\"bg-warning text-white rounded-circle p-3\"><i class=\"fas fa-layer-group fa-2x\"></i></div></div><small class=\"text-muted\">Учебные группы</small></div></div></div><div class=\"col-md-3\"><div class=\"card border-info\"><div class=\"card-body\"><div class=\"d-flex justify-content-between align-items-center\"><div><h6 class=\"card-title text-muted\">Дисциплины</h6><h3 class=\"mb-0\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var6 string
		templ_7745c5c3_Var6, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("%d", stats.TotalDisciplines))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/views/pages/admin/dashboard.templ`, Line: 81, Col: 67}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var6))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "</h3></div><div class=\"bg-info text-white rounded-circle p-3\"><i class=\"fas fa-book fa-2x\"></i></div></div><small class=\"text-muted\">Активные курсы</small></div></div></div></div><!-- Быстрые действия --><div class=\"row\"><div class=\"col-md-6\"><div class=\"card\"><div class=\"card-header\"><h5 class=\"card-title mb-0\">Быстрые действия</h5></div><div class=\"card-body\"><div class=\"row g-3\"><div class=\"col-md-6\"><a href=\"/admin/students?status=pending\" class=\"btn btn-warning w-100 mb-2\"><i class=\"fas fa-user-clock me-2\"></i>Подтвердить студентов</a></div><div class=\"col-md-6\"><a href=\"/admin/teachers\" class=\"btn btn-primary w-100 mb-2\"><i class=\"fas fa-user-plus me-2\"></i>Добавить преподавателя</a></div><div class=\"col-md-6\"><a href=\"/admin/groups\" class=\"btn btn-success w-100 mb-2\"><i class=\"fas fa-plus-circle me-2\"></i>Создать группу</a></div><div class=\"col-md-6\"><a href=\"/admin/disciplines\" class=\"btn btn-info w-100 mb-2\"><i class=\"fas fa-book-medical me-2\"></i>Добавить дисциплину</a></div></div></div></div></div><div class=\"col-md-6\"><div class=\"card\"><div class=\"card-header\"><h5 class=\"card-title mb-0\">Недавняя активность</h5></div><div class=\"card-body\"><div class=\"list-group list-group-flush\"><div class=\"list-group-item\"><div class=\"d-flex w-100 justify-content-between\"><h6 class=\"mb-1\">Новые работы</h6><small>Сегодня</small></div><p class=\"mb-1\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var7 string
		templ_7745c5c3_Var7, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("Загружено %d лабораторных работ", stats.RecentReports))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/views/pages/admin/dashboard.templ`, Line: 140, Col: 103}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var7))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "</p></div><div class=\"list-group-item\"><div class=\"d-flex w-100 justify-content-between\"><h6 class=\"mb-1\">Ожидают проверки</h6><small>В этом месяце</small></div><p class=\"mb-1\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var8 string
		templ_7745c5c3_Var8, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("%d лабораторных работ", stats.TotalLabs))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/views/pages/admin/dashboard.templ`, Line: 148, Col: 95}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var8))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "</p></div></div></div></div></div></div><!-- Навигация по разделам --><div class=\"row mt-4\"><div class=\"col-12\"><div class=\"card\"><div class=\"card-header\"><h5 class=\"card-title mb-0\">Управление системой</h5></div><div class=\"card-body\"><div class=\"row\"><div class=\"col-md-3 mb-3\"><div class=\"card h-100 border\"><div class=\"card-body text-center\"><div class=\"mb-3\"><i class=\"fas fa-users fa-3x text-primary\"></i></div><h5>Студенты</h5><p class=\"text-muted small\">Управление студентами, подтверждение регистрации</p><a href=\"/admin/students\" class=\"btn btn-outline-primary btn-sm\">Перейти</a></div></div></div><div class=\"col-md-3 mb-3\"><div class=\"card h-100 border\"><div class=\"card-body text-center\"><div class=\"mb-3\"><i class=\"fas fa-chalkboard-teacher fa-3x text-success\"></i></div><h5>Преподаватели</h5><p class=\"text-muted small\">Регистрация и управление преподавателями</p><a href=\"/admin/teachers\" class=\"btn btn-outline-success btn-sm\">Перейти</a></div></div></div><div class=\"col-md-3 mb-3\"><div class=\"card h-100 border\"><div class=\"card-body text-center\"><div class=\"mb-3\"><i class=\"fas fa-layer-group fa-3x text-warning\"></i></div><h5>Группы</h5><p class=\"text-muted small\">Создание и управление учебными группами</p><a href=\"/admin/groups\" class=\"btn btn-outline-warning btn-sm\">Перейти</a></div></div></div><div class=\"col-md-3 mb-3\"><div class=\"card h-100 border\"><div class=\"card-body text-center\"><div class=\"mb-3\"><i class=\"fas fa-book fa-3x text-info\"></i></div><h5>Дисциплины</h5><p class=\"text-muted small\">Управление учебными дисциплинами и курсами</p><a href=\"/admin/disciplines\" class=\"btn btn-outline-info btn-sm\">Перейти</a></div></div></div></div></div></div></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
